//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class car
    {
        public int Id { get; set; }
        public string Matricule { get; set; }
        public string Categories { get; set; }
        public string Puissance { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Name { get; set; }
        public string Price { get; set; }
        public string Image { get; set; }
        public string url_image { get; set; }
    }
}
